[settings]
dotfiles.root = "~/.config/mise/dotfiles"
dotfiles.default_mode = "symlink"

[settings.npm]
package_manager = "pnpm"

[dotfiles]
"~/.gitconfig" = {}

[dotfiles.".config/zellij"]
mode = "symlink-each"
variants = [
    { os = "windows", target = "~/AppData/Roaming/Zellij/config" },
    { os = "unix", target = "~/.config/zellij" },
]

[tools]
cmake = "latest"
deno = "latest"
docker-cli = "latest"
docker-compose = "latest"
fd = "latest"
ffmpeg = "latest"
fzf = "latest"
lazydocker = "latest"
neovim = "latest"
ninja = "latest"
node = "lts"
opencode = "latest"
ripgrep = "latest"
rust = "latest"
starship = "latest"
tree-sitter = "latest"
uv = "latest"
zellij = "latest"
zoxide = "latest"
pnpm = "latest"

# Other package managers
"pipx:basedpyright" = "latest"
"npm:typescript" = "7"
"npm:tsx" = "latest"
